Rework actix
WebThingsIO/webthing-rust pull request #67
Opened 2022-04-06 10:26 UTC by lu-zero

This should pave the way for testing things using the actix testing harness. See #66

2022-04-07 13:47 UTC, arpad-m requested changes
In addition to my inline comment `hosts.clone()` is unneccessary, one can just use `hosts`.

2022-04-07 13:47 UTC, arpad-m commented on src/server.rs
> +        let mut hosts = vec!["localhost".to_owned(), format!("localhost:{}", port)];
The code that builds `hosts` can be removed entirely, `hosts` is used nowhere in the `start` function.

2022-04-07 14:25 UTC, lu-zero commented
> In addition to my inline comment `hosts.clone()` is unneccessary, one can just use `hosts`.

I did not change much the code from its initial state, we should make a run and remove spurious clones later.

2022-10-01 14:35 UTC, tim-hellhake approved these changes

2022-10-01 14:35 UTC, merged

2022-10-01 14:35 UTC, tim-hellhake commented
Nice cleanup!